OnlineStore/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from ecomapp.views import \
    base_view, \
    product_view, \
    category_view, \
    cart_view, \
    add_to_cart_view, \
    remove_from_cart_view, \
    change_item_quantity, \
    checkout_view, \
    order_create_view, \
    make_order_view, \
    thank_you_view, \
    account_view, \
    registration_view, \
    login_view

urlpatterns = [
    path('', base_view, name='base'),
    path('product/<product_slug>', product_view, name='product_detail'),
    path('category/<category_slug>', category_view, name='category_detail'),
    path('cart', cart_view, name='cart'),
    path('add_to_cart', add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart', remove_from_cart_view, name='remove_from_cart'),
    path('change_item_quantity', change_item_quantity, name='change_item_quantity'),
    path('checkout', checkout_view, name='checkout'),
    path('order', order_create_view, name='create_order'),
    path('make_order', make_order_view, name='make_order'),
    path('thanks', thank_you_view, name='thank_you'),
    path('account', account_view, name='account'),
    path('registration', registration_view, name='registration'),
    path('login', login_view, name='login'),
    path('logout', LogoutView.as_view(next_page='base'), name='logout')
]

ecomapp/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.utils.text import slugify
from transliterate import translit # can translit words from kirill to latin
from django.urls import reverse
from decimal import Decimal
from django.utils import timezone


# Function to save a picture to a specific folder with a readable name
def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


def big_image_folder(instance, filename):
    filename = 'big-' + instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(instance.name, reversed=True)) # translit kirill to latin
        instance.slug = slug

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True) # can be empty, it is need for pre_save

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})


# connection function pre_save_category_slug and model Category
pre_save.connect(pre_save_category_slug, sender=Category)


class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# redefinition standart manager
class ProductManager(models.Manager):
    def all(self, *arg, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder) # need to install pillow
    big_image = models.ImageField(upload_to=big_image_folder, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2) # max_digits - count of digits in number, decimal_places - count of digits after comma
    available = models.BooleanField(default=True) # if default - product is available
    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item for product {0}".format(self.product.title)


class Cart(models.Model):
    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product):
        check = True
        for cart_item in self.items.all():
            if cart_item.product.slug == product.slug:
                check = False
                break
        if check:
            new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
            self.items.add(new_item)
            self.save()

    def remove_from_cart(self, product):
        for cart_item in self.items.all():
            if cart_item.product == product:
                self.items.remove(cart_item)
                self.save()

    def change_quantity(self, cart_item, quantity):
        cart_item.quantity = int(quantity)
        cart_item.item_total = int(quantity) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in self.items.all():
            new_cart_total += float(item.item_total)
        self.cart_total = new_cart_total
        self.save()


ORDER_STATUS_CHOICES = (
    ('Принят в обработку', 'Принят в обработку'),
    ('Выполняется', 'Выполняется'),
    ('Оплачен', 'Оплачен')
)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ForeignKey(Cart, on_delete=models.CASCADE, default=Cart().save())
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    buying_type = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')),
                                   default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    date_of_receiving = models.DateField(default=timezone.now())
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return "Заказ №{0}".format(str(self.id))

ecomapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth import login, authenticate
from ecomapp.forms import OrderForm, RegistrationForm, LoginForm
from ecomapp.models import Category, Product, Brand, CartItem, Cart, Order

# Create your views here.


def base_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    products = Product.objects.all().order_by('category')

    context = {
        'categories': categories,
        'products': products,
        'cart': cart
    }
    return render(request, 'base.html', context)


def product_view(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    product = Product.objects.get(slug = product_slug)
    context = {
        'categories': categories,
        'product': product,
        'cart': cart
    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    category = Category.objects.get(slug = category_slug)
    products_of_category = Product.objects.filter(category=category) # get all products from this category

    context = {
        'categories': categories,
        'category': category,
        'products_of_category': products_of_category,
        'cart': cart
    }
    return render(request, 'category.html', context)


def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'cart.html', context)


def add_to_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse(
        {
            'cart_total': cart.items.count()
        }
    )


def remove_from_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse(
        {
            'cart_total': cart.items.count(),
            'cart_total_price': cart.cart_total
        }
    )


def change_item_quantity(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    quantity = request.GET.get('quantity')
    item_id = request.GET.get('item_id')
    cart_item = CartItem.objects.get(id=int(item_id))
    cart.change_quantity(cart_item, quantity)
    return JsonResponse(
        {
            'cart_total': cart.items.count(),
            'item_total': cart_item.item_total,
            'cart_total_price': cart.cart_total
        }
    )


def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories
    }
    return render(request, 'checkout.html', context)


def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    form = OrderForm(request.POST or None)
    context = {
        "form": form,
        "cart": cart,
        "categories": categories
    }
    return render(request, 'order.html', context)


def make_order_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        date_of_receiving = form.cleaned_data['date']
        comments = form.cleaned_data['comments']
        new_order = Order.objects.create(
            user=request.user,
            items=cart,
            total=cart.cart_total,
            first_name=name,
            last_name=last_name,
            phone=phone,
            buying_type=buying_type,
            comments=comments,
            address=address,
            date_of_receiving=date_of_receiving
        )
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse('thank_you'))


def thank_you_view(request):
    categories = Category.objects.all()
    return render(request, 'thank_you.html', {"categories": categories})


def account_view(request):
    categories = Category.objects.all()
    order = Order.objects.filter(user=request.user).order_by('-id')
    context = {
        'order': order,
        "categories": categories
    }
    return render(request, 'account.html', context)


def registration_view(request):
    categories = Category.objects.all()
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        new_user = form.save(commit=False)
        new_user.username = username
        new_user.set_password(password)
        new_user.email = email
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'registration.html', context)


def login_view(request):
    categories = Category.objects.all()
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'login.html', context)

ecomapp/templates/account.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="text-center">Личный кабинет пользовтаеля {{ request.user }}</h3>
    <hr>
    <h4 class="text-center">Ваши заказы</h4>
    <table class="table">
        <tr style="background:lightblue;">
                <td class="text-center">Номер заказа</td>
                <td class="text-center">Дата создания заказа</td>
                <td class="text-center">Дата получения заказа</td>
                <td class="text-center">Статус заказа</td>
                <td class="text-center">Стоимость заказа</td>
                <td class="text-center">Детали заказа</td>
                <td class="text-center"></td>
            </tr>
        {% for item in order %}
            <tr>
                <td class="text-center" style="padding-top:20px; padding-bottom: 20px;">{{ item.id }}</td>
                <td class="text-center" style="padding-top:20px; padding-bottom: 20px;">{{ item.date }}</td>
                <td class="text-center" style="padding-top:20px; padding-bottom: 20px;">{{ item.date_of_receiving }}</td>
                <td class="text-center" style="padding-top:20px; padding-bottom: 20px;">{{ item.status }}</td>
                <td class="text-center" style="padding-top:20px; padding-bottom: 20px;">{{ item.total }} руб.</td>
                <td class="text-center" style="padding-top:20px; padding-bottom: 20px;">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal-{{ item.id }}">
                        Детали заказа
                    </button>
                </td>
            </tr>
        {% endfor %}
    </table>
    {% for item in order %}
        <!-- Modal -->
            <div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Заказ № {{ item.id }}</h4>
                  </div>
                  <div class="modal-body">
                    <h3>Товар</h3>
                    <table class="table">
                        {% for order_item in item.items.items.all %}
                                <tr>
                                    <td>{{ order_item.product.title }}</td>
                                    <td>{{ order_item.quantity }} шт.</td>
                                    <td>{{ order_item.item_total }} руб.</td>
                                </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td><strong>Итого: </strong></td>
                            <td><strong>{{ item.total }} руб.</strong></td>
                        </tr>
                    </table>
                    <h3>Заказчик</h3>
                    <p>Имя: {{ item.first_name }}</p>
                    <p>Фамилия: {{ item.last_name }}</p>
                    <p>Телефон: {{ item.phone }}</p>
                    <h4>Тип доставки</h4>
                    <p>
                        {% if item.buying_type == 'self' %}
                            Самовывоз
                        {% else %}
                            Доставка
                        {% endif %}
                    </p>
                    {% if item.buying_type == 'delivery' %}
                        <p>Адрес: {{ item.address }}</p>
                    {% endif %}
                    <h4>Комментарии к заказу</h4>
                    <p>{{ item.comments }}</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                  </div>
                </div>
              </div>
            </div>
    {% endfor %}
{% endblock content %}

ecomapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="text-center">Ваша корзина</h3>
    <br>
    {% if cart.items.count > 0 %}
        <div class="my-cart">
            <table class="table">
                <tr>
                    <td class="text-center"><strong>Товар</strong></td>
                    <td class="text-center"><strong>Количество</strong></td>
                    <td class="text-center"><strong>Цена</strong></td>
                    <td class="text-center"></td>
                </tr>
            {% for item in cart.items.all %}
                <tr class="cart-item-{{ item.product.id }}">
                    <td class="text-center">{{ item.product.title }}</td>
                    <td class="text-center">
                        <form action="" method="GET">
                            <input type="number" name="quantity" class="cart-item-quantity" data-id="{{ item.id }}" value="{{ item.quantity }}" min="1" style="width: 50px;">
                        </form>
                    </td>
                    <td class="text-center" id="cart-item-total-{{ item.id }}">{{ item.item_total }} руб.</td>
                    <td class="text-center">
                        <a href="#" class="remove_from_cart" data-slug="{{ item.product.slug }}" data-id="{{ item.product.id }}">
                            <button class="btn btn-default">Удалить из корзины</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
                <tr>
                    <td></td>
                    <td class="text-center"><strong>Итого: </strong></td>
                    <td class="text-center" id="cart_total_price"><strong>{{ cart.cart_total }} руб.</strong></td>
                    <td></td>
                </tr>
            </table>
            <br>
            <a href="{% url 'checkout' %}" class="pull-right">
                <button class="brn btn-info">Предварительный заказ</button>
            </a>
        </div>
    {% else %}
        <h3 class="text-center">Ваша корзина пуста</h3>
    {% endif %}
    <h3 class="text-center cart-empty" style="display:none;">Ваша корзина пуста</h3>
    <script>
        $(document).ready(function(){
            $('.remove_from_cart').on('click', function(e){
                e.preventDefault(); // Turn off standart actions
               product_slug = $(this).attr('data-slug');
               item_product_id = $(this).attr('data-id');
                data = {
                   product_slug: product_slug
               };
               $.ajax(
                   {
                       type: "GET",
                       url: "{% url 'remove_from_cart' %}",
                       data: data,
                       success: function(data){
                           $('#cart_count').html(data.cart_total);
                           $('.cart-item-' + item_product_id).css('display', 'none');
                           $('#cart_total_price').html('<strong>'+parseFloat(data.cart_total_price).toFixed(2)+' руб. </strong>')
                           if(parseInt(data.cart_total) == 0){
                               $('.my-cart').css('display', 'none');
                               $('.cart-empty').css('display', 'block');
                           }
                       }
                   }
               );
            });
        });

        $(document).ready(function(){
            $('.cart-item-quantity').on('click', function(){
                quantity = $(this).val();
                item_id = $(this).attr('data-id');
                data = {
                    quantity: quantity,
                    item_id: item_id
                };
                $.ajax(
                    {
                        type: "GET",
                        url: "{% url 'change_item_quantity' %}",
                        data: data,
                        success: function(data){
                            $('#cart-item-total-' + item_id).html(parseFloat(data.item_total).toFixed(2) + ' руб.'); // parseFloat - transforms item_total to Float, toFixed - shows amount number after comma
                            $('#cart_total_price').html('<strong>'+parseFloat(data.cart_total_price).toFixed(2)+' руб. </strong>')
                        }
                    }
                );
            });
        });
    </script>
{% endblock content %}

ecomapp/templates/category.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-sm-12">
        <h2>{{ category.name }}</h2>
        <hr>
        {% for product in products_of_category %}
            <div class="col-sm-4" style="margin-top: 20px;">
                <a href="{{ product.get_absolute_url }}"><img src="{{ product.big_image.url }}" alt="" style="width:100%; height: 200px;"></a>
                <h4 class="text-center"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h4>
                <p class="text-center" style="font-size:25px;"><strong>{{ product.price }} руб.</strong></p>
                {% if request.user.is_authenticated %}
                    <p class="text-center"><a href="#" class="add_to_cart" data-slug="{{ product.slug }}"><button class="btn btn-danger">Добавить в корзину</button></a></p>
                {% else %}
                    <p class="text-center">Заказывать товар могут только авторизованные пользователи. Пожалуйста, <a
                    href="#">войдите</a> или <a href="#">зарегистрируйтесь</a></p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <script>
        $(document).ready(function(){
            $('.add_to_cart').on('click', function(e){
                e.preventDefault() // Turn off standart actions
               product_slug = $(this).attr('data-slug');
               data = {
                   product_slug: product_slug
               };
               $.ajax(
                   {
                       type: "GET",
                       url: '{% url "add_to_cart" %}',
                       data: data,
                       success: function(data){
                           $("#cart_count").html(data.cart_total);
                       }
                   }
               );
            });
        });
    </script>
{% endblock content %}

ecomapp/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="text-center">Ваш предварительный заказ</h3>
    <br>
    <table class="table">
        <tr>
            <td class="text-center"><strong>Товар</strong></td>
            <td class="text-center"><strong>Количество</strong></td>
            <td class="text-center"><strong>Цена</strong></td>
            <td class="text-center"></td>
        </tr>
    {% for item in cart.items.all %}
        <tr>
            <td class="text-center">{{ item.product.title }}</td>
            <td class="text-center">{{ item.quantity }}</td>
            <td class="text-center">{{ item.item_total }} руб.</td>
            <td class="text-center"></td>
        </tr>
    {% endfor %}
        <tr>
            <td></td>
            <td class="text-center"><strong>Итого: </strong></td>
            <td class="text-center" id="cart_total_price"><strong>{{ cart.cart_total }} руб.</strong></td>
            <td></td>
        </tr>
    </table>
    <a href="{% url "create_order" %}" class="pull-right">
        <button class="btn btn-success">Оформить заказ</button>
    </a>
{% endblock content %}

ecomapp/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h3 class="text-center">Авторизация</h3>
    <hr>
    <div class="col-sm-8 col-sm-offset-2">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success btn-block" value="Войти в систему">
        </form>
    </div>
{% endblock content %}

ecomapp/templates/order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form action="{% url 'make_order' %}" method="POST">
        {% csrf_token %}
        <div class="col-sm-4">
            {{ form.name|as_crispy_field }}
        </div>
        <div class="col-sm-4">
            {{ form.last_name|as_crispy_field }}
        </div>
        <div class="col-sm-4">
            {{ form.phone|as_crispy_field }}
        </div>
        {{ form.buying_type|as_crispy_field }}
        {{ form.address|as_crispy_field }}
        {{ form.date|as_crispy_field}}
        {{ form.comments|as_crispy_field }}
        <input type="submit" class="btn btn-success" value="Оформить заказ">
    </form>
    <script>
        $(document).ready(function(){
            $('#div_id_address').css('display', 'none');
            $('#id_buying_type').on('click', function(){
                buying_type = $(this).val();
                if(buying_type == 'delivery') {
                    $('#div_id_address').css('display', 'block');
                } else {
                    $('#div_id_address').css('display', 'none');
                }
            });
            $('#id_date_month').css('width', '100px');
            $('#id_date_month').css('display', 'inline');
            $('#id_date_month').css('margin-right', '5px');
            $('#id_date_year').css('width', '200px');
            $('#id_date_year').css('display', 'inline');
            $('#id_date_year').css('margin', '5px');
            $('#id_date_day').css('width', '100px');
            $('#id_date_day').css('display', 'inline');
            $('#id_date_day').css('margin', '5px');
        });
    </script>
{% endblock content %}

ecomapp/templates/product.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-sm-4">
        <img src="{{ product.big_image.url }}" alt="" style="width:100%; height:100%;">
    </div>
    <div class="col-sm-8">
        <h3 class="text-center">{{ product.title }}</h3>
        <p>{{ product.description }}</p>
        <hr>
        <p style="font-size:25px;">Цена: <strong>{{ product.price }}</strong></p>
        {% if request.user.is_authenticated %}
            <a href="#" class="add_to_cart" data-slug="{{ product.slug }}"><button class="btn btn-danger">Добавить в корзину</button></a>
        {% else %}
            <p class="text-center">Заказывать товар могут только авторизованные пользователи. Пожалуйста, <a
                    href="{% url "login" %}">войдите</a> или <a href="{% url "registration" %}">зарегистрируйтесь</a></p>
        {% endif %}
    </div>
    <script>
        $(document).ready(function(){
            $('.add_to_cart').on('click', function(e){
                e.preventDefault() // Turn off standart actions
               product_slug = $(this).attr('data-slug');
               data = {
                   product_slug: product_slug
               };
               $.ajax(
                   {
                       type: "GET",
                       url: '{% url "add_to_cart" %}',
                       data: data,
                       success: function(data){
                           $("#cart_count").html(data.cart_total);
                       }
                   }
               );
            });
        });
    </script>
{% endblock content %}